project_id = "pxuqymgvmyuomafjgjuz"

[functions.create-payment]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.verify-payment]
verify_jwt = true

[functions.easyparcel-rates]
verify_jwt = true

[functions.easyparcel-create]
verify_jwt = true

[functions.easyparcel-track]
verify_jwt = true

[functions.mapbox-token]
verify_jwt = false

[functions.vendor-balance]
verify_jwt = true

[functions.rider-claim-delivery]
verify_jwt = true

[functions.rider-update-delivery]
verify_jwt = true

[functions.rider-balance]
verify_jwt = true

[functions.admin-users]
verify_jwt = true

[functions.stripe-config]
verify_jwt = false

[functions.create-embedded-checkout]
verify_jwt = true

[functions.rebroadcast-delivery]
verify_jwt = true

[functions.log-audit]
verify_jwt = true
