project_id = "pxuqymgvmyuomafjgjuz"

[functions.create-payment]
verify_jwt = false

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.verify-payment]
verify_jwt = true

[functions.easyparcel-rates]
verify_jwt = true

[functions.easyparcel-create]
verify_jwt = true

[functions.easyparcel-track]
verify_jwt = true
