// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pxuqymgvmyuomafjgjuz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB4dXF5bWd2bXl1b21hZmpnanV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2OTI3NjcsImV4cCI6MjA3MDI2ODc2N30._0cfhA6GaeVPK4hkU7imVSSgUW6tShozBXZ_ztqc8I8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});